### ISSUE TITLE
Distribute wheels for Windows in PyPI

### ISSUE THREAD

**Issue by tats-u** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#17]
This project Cython, which requires Visual Studio 2015, not the latest version.  I suppose that it is not good to make users install the not-latest version of VS only for Python modules, and is necessary to distribute wheels for Windows
I think that it wheels for Linux and Mac are not required because they adopt only one type of C++ compiler (GCC for Linux and Clang for macOS) and C++ run-time as usual one while Windows has many version of Visual Studio and C++ run-time.

**Comment by JeremyCCHsu** [comment]
Sorry that I don't write/run code on Windows, and I'm not familiar with the problem in Windows environments... If anyone has a solution to this, I'll be grateful.

**Comment by JeremyCCHsu** [comment]
It occurs to me that AppVeyor actually stores the wheel. Thus, I retrieved them and distribute the windows whl to PYPI. Thank you @tats-u for the script. I'd also like to ask whether there's an automatic way to distribute `whl` files. We could've added `twine upload dist/*` under `deploy_script`, but it doesn't seem right to run that part for *every Github push*, is it? Do you have a better idea about how to distribute `whl` in a more sensible way? Thank you!

**Comment by tats-u** [comment]
I suppose so.  It may help you to see https://www.appveyor.com/docs/branches/, https://www.appveyor.com/docs/deployment/, https://www.appveyor.com/docs/environment-variables/, https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables.

1. Set `$TWINE_USERNAME` and `$TWINE_PASSWORD` (don't write to YAMLs directly) like:

```yaml
environment:
  TWINE_USERNAME: JeremyCCHsu
  matrix:
    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda3-x64
      
    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
MINICONDA: C:\Miniconda3
```

```yaml
env:
  global:
    - TWINE_USERNAME=JeremyCCHsu
```

2. Check the environment variable(s) `$APPVEYOR_REPO_TAG` and `APPVEYOR_REPO_TAG_NAME` (AppVeyor) or `$TRAVIS_TAG` (Travis).  If the commit is tagged, execute twine.

```yaml
after_test:
  - ps: |
      $ErrorActionPreference = "Stop"
      if($APPVEYOR_REPO_TAG -eq "true" -and $APPVEYOR_REPO_TAG_NAME -match "^v([0-9.]+)$") {
        conda install -y twine
        python setup.py bdist_wheel
        twine dist\*
      }
```

```yaml
script:
  - cd demo
  - python demo.py
  - |
    if [[ $TRAVIS_TAG =~ ^v([0-9.]+)$ ]]; then
      pip install twine
      python setup.py sdist 
      twine dist/*
    fi

```
